@startuml
set separator none
title System - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Person(User, "User", $descr="", $tags="", $link="")
System(System, "System", $descr="", $tags="", $link="")

Rel(User, System, "Use the system", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml